### ISSUE TITLE
error with postgresql

### ISSUE THREAD

**Issue by KatiaSishost** [wazo-platform/wazo-ansible#124]
TASK [geerlingguy.postgresql : Configure global settings.] **************************************************************************************************************
failed: [localhost] (item={'option': 'port', 'value': '5432'}) => {"ansible_loop_var": "item", "changed": false, "item": {"option": "port", "value": "5432"}, "msg": "Destination /etc/postgresql/13/main/postgresql.conf does not exist !", "rc": 257}

**Comment by DrPyser** [comment]
Hi, Wazo developer here.

I'll redirect you to our [community forum](https://wazo-platform.discourse.group) or our [community mattermost](https://mm.wazo.community/wazo-platform) for support and communications with the wazo team and other community members.

Thank you!
