### ISSUE TITLE
Debian 10 Ansible Error

### ISSUE THREAD

**Issue by miguemely** [wazo-platform/wazo-ansible#38]
New install of Debian 10, following the guide on the install website, I reach an error using the ansible playbook. For sanity sake, I'm just running apt install asterisk to show the error, as its an issue processing asterisk:

`Setting up asterisk (8:16.6.1-1~wazo2.deb10) ...
Job for asterisk.service failed because the control process exited with error code.
See "systemctl status asterisk.service" and "journalctl -xe" for details.
invoke-rc.d: initscript asterisk, action "start" failed.
● asterisk.service - Asterisk PBX
   Loaded: loaded (/lib/systemd/system/asterisk.service; enabled; vendor preset: enabled)
  Drop-In: /usr/lib/systemd/system/asterisk.service.d
           └─wazo-asterisk-config.conf
   Active: failed (Result: exit-code) since Thu 2019-11-28 01:55:47 EST; 6ms ago
  Process: 19314 ExecStartPre=/bin/sh -c /usr/bin/wazo-confgen asterisk/modules.conf > /etc/asterisk/modules.conf (code=exited, status=127)

Nov 28 01:55:47 pbx01 systemd[1]: Starting Asterisk PBX...
Nov 28 01:55:47 pbx01 sh[19314]: /bin/sh: 1: /usr/bin/wazo-confgen: not found
Nov 28 01:55:47 pbx01 systemd[1]: asterisk.service: Control process exited, code=exited, status=127/n/a
Nov 28 01:55:47 pbx01 systemd[1]: asterisk.service: Failed with result 'exit-code'.
Nov 28 01:55:47 pbx01 systemd[1]: Failed to start Asterisk PBX.
dpkg: error processing package asterisk (--configure):
 installed asterisk package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 asterisk
E: Sub-process /usr/bin/dpkg returned an error code (1)`

`PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

**Comment by fblackburn1** [comment]
Should be fixed with https://github.com/wazo-platform/wazo-ansible/pull/36
The current dev version is broken and should be fixed soon
