### ISSUE TITLE
Wazo Install Fail - Debian 10 Ansible

### ISSUE THREAD

**Issue by Maxime-Car** [wazo-platform/wazo-ansible#40]
Hi, 
Problem with a fresh install of wazo 19.7 :

- Debian 10 buster
- 4 vcpu
- 4 Go RAM

Follwing install tutorial from **https://wazo-platform.org/install**

- Setp 1 to 5 OK
- Step 6

`ansible-playbook -i inventories/uc-engine uc-engine.yml

PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [preflight_checks : Assert Debian Buster] ********************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [preflight_checks : Validate database names] *****************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [preflight_checks : Assert root password for setup] **********************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [preflight_checks : Assert UTF-8 locale] *********************************************************************************************************************************************************************
changed: [127.0.0.1]

PLAY [database,b2bua,engine-api] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian_upgrade_first : Upgrade Debian before anything] ******************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY [database] ***************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [wazo_db : Ensure PostgreSQL packages are installed.] ********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [wazo_db : Configure client auth] ****************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [wazo_db : Install sudo] *************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [wazo_db : Ensure PostgreSQL Python libraries are installed.] ************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Change PostgreSQL port] *************************************************************************************************************************************************************************************

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/variables.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Include OS-specific variables (Debian).] *******************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Include OS-specific variables (RedHat).] *******************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Include OS-specific variables (Fedora).] *******************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_packages.] *******************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_version.] ********************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_daemon.] *********************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_data_dir.] *******************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_bin_path.] *******************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_config_path.] ****************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/setup-Debian.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Ensure PostgreSQL Python libraries are installed.] *********************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL packages are installed.] *****************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure all configured locales are present.] ****************************************************************************************************************************************
ok: [127.0.0.1] => (item=en_US.UTF-8)

TASK [geerlingguy.postgresql : Force-restart PostgreSQL after new locales are generated.] *************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/initialize.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Set PostgreSQL environment variables.] *********************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL data directory exists.] ******************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Check if PostgreSQL database is initialized.] **************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL database is initialized.] ****************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/configure.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Configure global settings.] ********************************************************************************************************************************************************
ok: [127.0.0.1] => (item={u'option': u'port', u'value': u'5432'})

TASK [geerlingguy.postgresql : Configure host based authentication (if entries are configured).] ******************************************************************************************************************
changed: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL unix socket dirs exist.] *****************************************************************************************************************************************
ok: [127.0.0.1] => (item=/var/run/postgresql)

TASK [geerlingguy.postgresql : Ensure PostgreSQL is started and enabled on boot.] *********************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.] **********************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] ******************************************************************************************************************************************

TASK [Set PostgreSQL superadmin password] *************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [Configure PostgreSQL] ***************************************************************************************************************************************************************************************

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/variables.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Include OS-specific variables (Debian).] *******************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Include OS-specific variables (RedHat).] *******************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Include OS-specific variables (Fedora).] *******************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_packages.] *******************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_version.] ********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_daemon.] *********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_data_dir.] *******************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_bin_path.] *******************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Define postgresql_config_path.] ****************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/setup-Debian.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Ensure PostgreSQL Python libraries are installed.] *********************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL packages are installed.] *****************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure all configured locales are present.] ****************************************************************************************************************************************
ok: [127.0.0.1] => (item=en_US.UTF-8)

TASK [geerlingguy.postgresql : Force-restart PostgreSQL after new locales are generated.] *************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/initialize.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Set PostgreSQL environment variables.] *********************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL data directory exists.] ******************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Check if PostgreSQL database is initialized.] **************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL database is initialized.] ****************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : include_tasks] *********************************************************************************************************************************************************************
included: /root/.ansible/roles/geerlingguy.postgresql/tasks/configure.yml for 127.0.0.1

TASK [geerlingguy.postgresql : Configure global settings.] ********************************************************************************************************************************************************
ok: [127.0.0.1] => (item={u'option': u'port', u'value': u'5432'})
ok: [127.0.0.1] => (item={u'option': u'listen_addresses', u'value': u'127.0.0.1'})

TASK [geerlingguy.postgresql : Configure host based authentication (if entries are configured).] ******************************************************************************************************************
changed: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL unix socket dirs exist.] *****************************************************************************************************************************************
ok: [127.0.0.1] => (item=/var/run/postgresql)

TASK [geerlingguy.postgresql : Ensure PostgreSQL is started and enabled on boot.] *********************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.] **********************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] ******************************************************************************************************************************************

RUNNING HANDLER [geerlingguy.postgresql : restart postgresql] *****************************************************************************************************************************************************
 [WARNING]: Ignoring "sleep" as it is not used in "systemd"

changed: [127.0.0.1]

PLAY [b2bua] ******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Install Wazo repo package source] ***************************************************************************************************************************************************************************

TASK [debian-repo-wazo : Install APT python bindings and GPG] *****************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Add Wazo distribution key] ***************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Gather packages facts] *******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Add bootstrap Wazo repository] ***********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [debian-repo-wazo : Install wazo-dist] ***********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Add persistent Wazo repository] **********************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [debian-repo-wazo : Remove bootstrap Wazo repository] ********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Install xivo-certs] *********************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [b2bua : Install custom certificate for HTTPS] ***************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Install custom private key for HTTPS] ***************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Remove generated files] *****************************************************************************************************************************************************************************
skipping: [127.0.0.1] => (item=/usr/share/xivo-certs/server.key)
skipping: [127.0.0.1] => (item=/usr/share/xivo-certs/server.crt)

TASK [b2bua : Install Asterisk] ***********************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [b2bua : Ensure Asterisk is started] *************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [b2bua : Create /etc/asterisk/extensions.d] ******************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [b2bua : Ensure Asterisk permissions] ************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [b2bua : Install Asterisk AGI configuration] *****************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [b2bua : Install Asterisk AMI configuration] *****************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Install Asterisk HTTP configuration] ****************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Install wazo-confgend-client] ***********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [b2bua : Install wazo-confgend-client config] ****************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Create xivo-sysconfd drop-in file directory] ********************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [b2bua : Install xivo-sysconfd drop-in file] *****************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [b2bua : Install xivo-sysconfd] ******************************************************************************************************************************************************************************
ok: [127.0.0.1]

PLAY [engine-api] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Install Wazo repo package source] ***************************************************************************************************************************************************************************

TASK [debian-repo-wazo : Install APT python bindings and GPG] *****************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Add Wazo distribution key] ***************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Gather packages facts] *******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Add bootstrap Wazo repository] ***********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [debian-repo-wazo : Install wazo-dist] ***********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debian-repo-wazo : Add persistent Wazo repository] **********************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [debian-repo-wazo : Remove bootstrap Wazo repository] ********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [Create/Configure SSL certs] *********************************************************************************************************************************************************************************

TASK [wazo_certs : Install xivo-certs] ****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [wazo_certs : Install custom certificate for HTTPS] **********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [wazo_certs : Install custom private key for HTTPS] **********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [wazo_certs : Remove generated files] ************************************************************************************************************************************************************************
skipping: [127.0.0.1] => (item=/usr/share/xivo-certs/server.key)
skipping: [127.0.0.1] => (item=/usr/share/xivo-certs/server.crt)

TASK [engine-api : Install wazo-confgend-client] ******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Install RabbitMQ] *******************************************************************************************************************************************************************************************

TASK [wazo_message_bus : Install RabbitMQ] ************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Create /var/lib/wazo] **************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Disable Wazo services] *************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api : Create wazo-calld config dir] ******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Add wazo-calld config] *************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api : Install wazo-calld] ****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Create wazo-amid config dir] *******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Add wazo-amid config] **************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api : Install wazo-amid] *****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Preconfigure database initialization] **********************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api : Create wazo-confd config dir] ******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Add wazo-confd config] *************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api : Create xivo-dao config dir] ********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Add xivo-dao config] ***************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api : Install wazo-confd] ****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Install wazo-confd-client-python3] *************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Create wazo-confgend config dir] ***************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Add wazo-confgend config] **********************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api : Install wazo-confgend] *************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Create wazo-agid config dir] *******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Add wazo-agid config] **************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api : Install xivo-config] ***************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Install wazo-agid] *****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Install wazo-websocketd] ***********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Install nginx] *********************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Install wazo-nginx] ****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Install wazo-provd] ****************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api : Enable Wazo services] **************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Install Wazo auth] ******************************************************************************************************************************************************************************************

TASK [wazo_auth : Preconfigure wazo-auth package] *****************************************************************************************************************************************************************
skipping: [127.0.0.1] => (item=wazo-auth/bootstrap-skip)
skipping: [127.0.0.1] => (item=wazo-auth/db-skip)

TASK [wazo_auth : Install wazo-auth] ******************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [wazo_auth : Create default wazo-auth database preconfiguration] *********************************************************************************************************************************************
changed: [127.0.0.1]

TASK [wazo_auth : Copy wazo-auth database preconfiguration if needed] *********************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [wazo_auth : Copy wazo-auth database preconfiguration template] **********************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [wazo_auth : Reset database options for wazo-auth package] ***************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [wazo_auth : Reconfigure database options for wazo-auth package] *********************************************************************************************************************************************
changed: [127.0.0.1]

TASK [wazo_auth : Initialize wazo-auth database] ******************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Create an index.html for the home page] ***************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api-init : Install wazo-auth-keys] *******************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api-init : Create service users with wazo-auth-keys] *************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Create default main database preconfiguration] ********************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Copy main database preconfiguration] ******************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [engine-api-init : Copy main database preconfiguration template] *********************************************************************************************************************************************
ok: [127.0.0.1]

TASK [engine-api-init : Reset main database options for wazo-auth package] ****************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Reconfigure main database options] ********************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Initialize main database] *****************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Fix Twisted dropin.cache] *****************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [engine-api-init : Start Wazo services] **********************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=wazo-agid)
changed: [127.0.0.1] => (item=wazo-amid)
changed: [127.0.0.1] => (item=wazo-confd)
changed: [127.0.0.1] => (item=wazo-confgend)
failed: [127.0.0.1] (item=wazo-calld) => {"changed": false, "item": "wazo-calld", "msg": "Unable to start service wazo-calld: Job for wazo-calld.service failed because the control process exited with error code.\nSee \"systemctl status wazo-calld.service\" and \"journalctl -xe\" for details.\n"}
changed: [127.0.0.1] => (item=wazo-provd)
changed: [127.0.0.1] => (item=wazo-websocketd)
        to retry, use: --limit @/home/wazo/wazo-ansible/uc-engine.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=103  changed=21   unreachable=0    failed=1`

Result for _systemctl status wazo-calld.service_ :
`root@wazo:/home/wazo/wazo-ansible# systemctl status wazo-calld.service
● wazo-calld.service - wazo-calld server
   Loaded: loaded (/lib/systemd/system/wazo-calld.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-11-29 14:45:13 CET; 37s ago
  Process: 30388 ExecStartPre=/usr/bin/install -d -o www-data -g www-data /run/wazo-calld (code=exited, status=0/SUCCESS)
  Process: 30389 ExecStart=/usr/bin/wazo-calld (code=exited, status=1/FAILURE)

nov. 29 14:45:13 wazo wazo-calld[30389]:   File "/usr/lib/python3/dist-packages/wazo_calld/controller.py", line 31, in __init__
nov. 29 14:45:13 wazo wazo-calld[30389]:     self.ari = CoreARI(config['ari'])
nov. 29 14:45:13 wazo wazo-calld[30389]:   File "/usr/lib/python3/dist-packages/wazo_calld/ari_.py", line 48, in __init__
nov. 29 14:45:13 wazo wazo-calld[30389]:     config['startup_connection_delay'],
nov. 29 14:45:13 wazo wazo-calld[30389]:   File "/usr/lib/python3/dist-packages/wazo_calld/ari_.py", line 66, in _new_ari_client
nov. 29 14:45:13 wazo wazo-calld[30389]:     raise ARIUnreachable(ari_config)
nov. 29 14:45:13 wazo wazo-calld[30389]: wazo_calld.exceptions.ARIUnreachable: ARI server unreachable... stopping
nov. 29 14:45:13 wazo systemd[1]: wazo-calld.service: Control process exited, code=exited, status=1/FAILURE
nov. 29 14:45:13 wazo systemd[1]: wazo-calld.service: Failed with result 'exit-code'.
nov. 29 14:45:13 wazo systemd[1]: Failed to start wazo-calld server.`

Result for _journalctl -xe_ :
`root@wazo:/home/wazo/wazo-ansible# journalctl -xe
nov. 29 14:47:27 wazo wazo-confd[30327]: 2019-11-29 14:47:27,575 [30327] (INFO) (service_discovery): registration failed, retrying in 2 seconds HTTPSConnectionPool(host='localhost', port=8500): Max retries excee
nov. 29 14:47:29 wazo wazo-confd[30327]: 2019-11-29 14:47:29,581 [30327] (ERROR) (STDERR): /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being
nov. 29 14:47:29 wazo wazo-confd[30327]: 2019-11-29 14:47:29,582 [30327] (ERROR) (STDERR):   InsecureRequestWarning)
nov. 29 14:47:29 wazo wazo-confd[30327]: 2019-11-29 14:47:29,583 [30327] (INFO) (flask.app): request: GET https://localhost:9486/1.1/infos {'Host': 'localhost:9486', 'User-Agent': 'python-requests/2.21.0', 'Acce
nov. 29 14:47:29 wazo wazo-confd[30327]: 2019-11-29 14:47:29,590 [30327] (INFO) (flask.app): response: (127.0.0.1) GET https://localhost:9486/1.1/infos 401
nov. 29 14:47:29 wazo wazo-confd[30327]: 2019-11-29 14:47:29,591 [30327] (INFO) (service_discovery): Registering wazo-confd on Consul as a3f92dcb-bfbd-49e6-939f-b83b6bf57b05 with 10.2.10.10:9486
nov. 29 14:47:29 wazo wazo-confd[30327]: 2019-11-29 14:47:29,592 [30327] (INFO) (service_discovery): registration failed, retrying in 2 seconds HTTPSConnectionPool(host='localhost', port=8500): Max retries excee
nov. 29 14:47:31 wazo wazo-confd[30327]: 2019-11-29 14:47:31,597 [30327] (ERROR) (STDERR): /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being
nov. 29 14:47:31 wazo wazo-confd[30327]: 2019-11-29 14:47:31,598 [30327] (ERROR) (STDERR):   InsecureRequestWarning)
nov. 29 14:47:31 wazo wazo-confd[30327]: 2019-11-29 14:47:31,599 [30327] (INFO) (flask.app): request: GET https://localhost:9486/1.1/infos {'Host': 'localhost:9486', 'User-Agent': 'python-requests/2.21.0', 'Acce
nov. 29 14:47:31 wazo wazo-confd[30327]: 2019-11-29 14:47:31,607 [30327] (INFO) (flask.app): response: (127.0.0.1) GET https://localhost:9486/1.1/infos 401
nov. 29 14:47:31 wazo wazo-confd[30327]: 2019-11-29 14:47:31,608 [30327] (INFO) (service_discovery): Registering wazo-confd on Consul as a3f92dcb-bfbd-49e6-939f-b83b6bf57b05 with 10.2.10.10:9486
nov. 29 14:47:31 wazo wazo-confd[30327]: 2019-11-29 14:47:31,609 [30327] (INFO) (service_discovery): registration failed, retrying in 2 seconds HTTPSConnectionPool(host='localhost', port=8500): Max retries excee
nov. 29 14:47:33 wazo wazo-confd[30327]: 2019-11-29 14:47:33,614 [30327] (ERROR) (STDERR): /usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being
nov. 29 14:47:33 wazo wazo-confd[30327]: 2019-11-29 14:47:33,615 [30327] (ERROR) (STDERR):   InsecureRequestWarning)`

Thanks in advance, let me know if missing something !

**Comment by fblackburn1** [comment]
Can you retry with latest commit?
The https://github.com/wazo-platform/wazo-ansible/pull/36 has just been merged

**Comment by Maxime-Car** [comment]
hi !

Issue solced, many thanks !
