### ISSUE TITLE
Install How-to: Python is missing as dependency

### ISSUE THREAD

**Issue by ymolinet** [wazo-platform/wazo-ansible#54]
Following this doc : https://wazo-platform.org/install
python is missing as package dependency. 

apt-get install -yq sudo git ansible python

**Comment by DrPyser** [comment]
Hi, Wazo developer here.

I'll redirect you to our [community forum](https://wazo-platform.discourse.group) or our [community mattermost](https://mm.wazo.community/wazo-platform) for support and communications with the wazo team and other community members.

Thank you!
