### ISSUE TITLE
Bug after install: 'wazo_ui.user.UserUI object' has no attribute 'get_instance_config'

### ISSUE THREAD

**Issue by prowwid** [wazo-platform/wazo-ansible#74]
Each time I'm trying to access the "Plugins" page, the system redirects to users section and displays the following error:
'wazo_ui.user.UserUI object' has no attribute 'get_instance_config'

I've tried installing Wazo following official [Ansible guide](https://wazo-platform.org/uc-doc/installation/install-system) on Debian 10 at Google Cloud Platform. 
I've tried installing both dev and stable versions.

Could anyone advise what might be the problem?

**Comment by sboily** [comment]
Hello, this bug is already in a WIP PR here wazo-ui https://github.com/wazo-platform/wazo-ui/pull/15
